Ignore delivery messages
rapidpro/android-channel pull request #12
Opened 2017-08-15 19:31 UTC by johncordeiro

This PR creates a new settings that allow users to insert an message to be ignored when received by the Android relayer.

In Brazil for example, some operators sends a SMS confirmation when a new message is sent. In this way we avoid it to be sent to RapidPRO and break flows.

2017-08-16 15:17 UTC, nicpottier requested changes

2017-08-16 15:17 UTC, nicpottier commented on app/src/main/java/io/rapidpro/androidchannel/IncomingSMSObserver.java
> +            selectionArgs = new String[]{"%" + ignoredMessage + "%"};
This seems like prone to SQL injection attacks (though it matters less in this case than a server). Might just be easier to do a substring match when we are actually doing the iteration.

2017-08-16 16:09 UTC, johncordeiro commented on app/src/main/java/io/rapidpro/androidchannel/IncomingSMSObserver.java
> +            selectionArgs = new String[]{"%" + ignoredMessage + "%"};
I would like to avoid useless iterations, but I agree that it could be done in a better way.

2017-09-27 13:14 UTC, johncordeiro commented
@nicpottier I updated the PR that checks in a safer way the ignored messages and also adds phone blacklist to avoid infinite loops when the mobile operator sends SMS.

2017-10-05 21:13 UTC, nicpottier commented on app/src/main/res/layout/settings.xml
> +            android:summary="Enter a text that when in the body of the message will not send it to the server"
"Ignore messages which contain this text"

2017-10-05 21:13 UTC, nicpottier commented on app/src/main/res/layout/settings.xml
> +            android:summary="Enter numbers that will be ignored when a message is received from them"
Ignore messages received from these numbers (comma separated)

2017-10-05 21:14 UTC, nicpottier commented on app/src/main/java/io/rapidpro/androidchannel/IncomingSMSObserver.java
> +                if (address.toLowerCase().contains(number.trim().toLowerCase())) {
May want to check that number is non-empty here (after trimming), if someone has a trailing comma then it would match all numbers.

2017-10-05 21:14 UTC, nicpottier commented on app/src/main/java/io/rapidpro/androidchannel/IncomingSMSObserver.java
> +                break;
Let's add a log for this case (as below)

2017-10-05 21:15 UTC, nicpottier commented
What's the infinite loop case? Shortcodes sending things? RapidPro should be catching those in theory, would love to have an example so we can fix that there if it occurring.

2017-10-09 17:55 UTC, johncordeiro commented
@nicpottier some shortcodes send a message and RapidPRO respond as "Answer with YES or NO", and shortcode sends it again and again.

2017-10-10 16:34 UTC, nicpottier commented
This isn't caught by?
  https://github.com/nyaruka/rapidpro/blob/master/temba/msgs/models.py#L1486

2018-08-23 18:13 UTC, ericnewcomer commented
@johncordeiro is there still interest in bringing this over the line or should we close it?

2024-07-17 19:37 UTC, closed without merging